openapi: 3.0.3
info:
  title: PowerUp Management API
  description: API para gestión de objetos - Generación automática de DTOs con OpenAPI
  version: 1.0.0
  contact:
    name: Pragma PowerUp Team

servers:
  - url: http://localhost:8081
    description: Servidor local de desarrollo


paths:
  /users:
    post:
      tags:
        - Users
      summary: Crear un nuevo usuario
      description: Crea un nuevo usuario en el sistema
      operationId: createUser
      requestBody:
        description: Datos del objeto a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: Objeto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    UserRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          example: "Juan"
        lastName:
          type: string
          minLength: 1
          maxLength: 100
          example: "Pérez"
        password:
          type: string
          minLength: 8
          maxLength: 100
          example: "MiClaveSegura123"
        email:
          type: string
          format: email
          example: "juan.perez@email.com"
        identificationDocument:
          type: string
          pattern: '^[0-9]+$'
          maxLength: 20
          example: "1234567890"
        phoneNumber:
          type: string
          maxLength: 14
          pattern: '^\+?[0-9]{1,13}$'
          example: "+573005698325"
        birthDate:
          type: string
          format: date
          example: "1990-01-01"
        role:
          type: string
      required:
        - name
        - lastName
        - password
        - email
        - identificationDocument
        - phoneNumber
        - birthDate

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único del objeto
          example: 1
        name:
          type: string
          description: Nombre del objeto
          example: "Objeto de ejemplo"
        lastName:
          type: string
          description: Descripción del objeto
          example: "Apellido"
        email:
          type: string
          description: Descripción del objeto
          example: "email@email.com"

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Timestamp del error
          example: "2025-11-29T10:30:00Z"
        status:
          type: integer
          description: Código de estado HTTP
          example: 400
        error:
          type: string
          description: Tipo de error
          example: "Bad Request"
        message:
          type: string
          description: Mensaje descriptivo del error
          example: "El campo 'name' es requerido"
        path:
          type: string
          description: Path de la petición que causó el error
          example: "/api/v1/objects"

